### ISSUE TITLE
JPA @Query sql error (dev용 db: h2사용중)

### ISSUE THREAD

**Issue by jisoo615** [jisoo615/myproject#1]
### [code](https://github.com/jisoo615/myproject/blob/d3f934bed9efbb66a16f7b1aaf3d5d2c89e7f5fb/src/main/java/com/example/myproject/repository/CommentRepository.java)
```
@Query("select c.id, c.board_id, c.parent_id, c.writer, c.deletedyn, c.created_date, c.modifed_date, " +
            " if(c.deletedyn='Y', 'deleted comment', c.content) as content "+
            " from comment c " +
            " where board_id = :boardId " +
            " order by c.parent_id Asc, c.id Asc"
, nativeQuery=true)
    List<Comment> findAllByboardIdOrderByParentIdAscIdAsc(Long boardId);
```

### error
1. syntax error
```
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: = near line 1, column 109 [select c.id, c.board_id, c.parent_id, c.writer, c.deletedyn, c.created_date, c.modifed_date, if(c.deletedyn=='Y', 'deleted comment', c.content) as content from comment c where board_id = #boardId order by c.parent_id Asc, c.id Asc]
	at org.hibernate.hql.internal.ast.QuerySyntaxException.convert(QuerySyntaxException.java:74)
	at org.hibernate.hql.internal.ast.ErrorTracker.throwQueryException(ErrorTracker.java:93)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:301)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:189)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:144)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:113)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:73)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:162)
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:636)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:748)
```

2. Param error
```
For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.; nested exception is java.lang.IllegalStateException: For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.
```
...

**Comment by jisoo615** [comment]
### solution
1. syntax error solution
* = 하나만
```
if(c.deletedyn=='Y', 'deleted comment', c.content)   ->   if(c.deletedyn='Y', 'deleted comment', c.content)
```

2. param error solution
* 외부에서 파라미터를 받아쓰려면  ```@Param``` 어노테이션이 필요
* 또한 객체일때와 표현이 다름 
> @Param("user") User user 일때
> ``` select u from user u where u.name = :#{#user.name} ```
> @Param("name") String name 일때
> ``` select u from user u where u.name = :name ```

**Comment by jisoo615** [comment]
### Q:  nativeQuery 는 무엇인가요?

**Comment by jisoo615** [comment]
### nativeQuery
* default 로 false를 가져 JPQL 사용을 명시
* true로 지정시 SQL 사용을 명시

### JPQL과 SQL의 차이
>JPQL의 특징
 - 애플리케이션 로딩 시점에 오류를 알려주고, 실행 전 IDE가 오류를 알려준다. SQL로 하면 테스트를 실행 해봐야 알수있다.
 - sql에 비해 복잡하거나 비효율적일 수 있다. 
 - 대소문자 구분
 - 엔터티 이름을 사용한다. ```@Entity(name="user")```으로 지정했던 객체 이름!
 - 별칭을 써야 한다. ```select u from user u```

> JPA를 사용하는데도 SQL을 사용하는 이유
 - 복잡하거나  jpql에서 지원하지 않는 특수한 쿼리가 필요할 때 사용한다.
 - 퍼포먼스 향상 위해 사용하기도 한다. JPQL
 -> 여러개의 레코드를 update 할때 jpa에서는 for문을 도는 레코드를 하나씩 update한다. 그러나 sql로 작성하면 ```UPDATE user SET age=20 WHERE id between 50 and 60``` 로 한번에 가능

**Comment by jisoo615** [comment]
### sql syntax error
### CommentRepository code
https://github.com/jisoo615/myproject/blob/76cf5c6e1c0df921b48da129b050f126864ca329/src/main/java/com/example/myproject/repository/CommentRepository.java#L12-L18

### error
``` 
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT C.ID, C.BOARD_ID, C.PARENT_ID, 
C.WRITER, C.DELETEDYN, C.CREATED_DATE, C.MODIFED_DATE, IF[*](C.DELETEDYN='Y', 'deleted comment', C.CONTENT) AS 
CONTENT FROM COMMENT C WHERE BOARD_ID = ? ORDER BY C.PARENT_ID ASC, C.ID ASC ";
 expected "*, NOT, EXISTS, INTERSECTS"; SQL statement:
```
* if()함수 사용 불가능 한것 같다. ( *, NOT, EXISTS, INTERSECTS 사용 가능)
* 위 메소드의 목적 : 삭제된 레코드도 함께 조회 해서, 삭제된 댓글의 content가 "deleted comment"로 보이게 하는것
### solution
1. native query 를 false로 바꾸어 정렬만 적용한 채 boardId에 맞는 모든 레코드 조회한다.
2. 프론트나 Service 에서 deletedyn이 'Y'일때 content를 "삭제된 댓글입니다" 로 바꾸어 보여주기

**Comment by jisoo615** [comment]
Thymeleaf 에서 ```th:if``` ```th:unless```태그에 deleted_yn 변수로 넣으면 제대로 작동 안함
js 코드에서 먼저 응답 데이터 처리해 th태그 없이 innerHTML로 보내면 잘 됨

**Comment by jisoo615** [comment]
### Thymeleaf를 처리하는 모델링을 담당하는 부분은 서버이다. 
타임리프 태그를 화면이 로딩 된 후 페이지에 집어넣는다고 해서 작동하지 않는다. 
서버에서 th태그를 읽고 처리하여 화면에 보여주기 때문
타임리프는 서버에서 처리한 데이터만을 보여준다.
